spring:
  sql:
    init:
      mode: always

# application-demo.yml
app:
  demo:
    admin:
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
      name: ${ADMIN_NAME}
      phone: ${ADMIN_PHONE}
