spring:
  sql:
    init:
      mode: always

# application-demo.yml
app:
  demo:
    admin:
      email: ${ADMIN_EMAIL:admin@test.com}
      password: ${ADMIN_PASSWORD:}
      name: ${ADMIN_NAME:관리자}
      phone: ${ADMIN_PHONE:010-9999-9999}
